name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - name: 上传EXE
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: dist/
